import { Router } from "express";
import { adminController } from "./controller";
import { requireAuth } from "../../middleware/auth";
import { requireRole } from "../../middleware/auth";
import { validateBody, validateQuery } from "../../middleware/validation";
import { listUsersQuerySchema, updateUserVerificationSchema } from "./schema";
export const adminRoutes = Router();
adminRoutes.use(requireAuth);
adminRoutes.use(requireRole("super_admin", "admin"));
adminRoutes.get("/users", validateQuery(listUsersQuerySchema), (req, res) => adminController.listUsers(req, res));
adminRoutes.patch("/users/:id/verification", validateBody(updateUserVerificationSchema), (req, res) => adminController.updateUserVerification(req, res));
adminRoutes.get("/dashboard", (req, res) => adminController.getDashboard(req, res));
adminRoutes.get("/inventory", (req, res) => adminController.getInventoryOverview(req, res));
