import { Router } from "express";
import { authController } from "./controller";
import { validateBody } from "../../middleware/validation";
import { requireAuth } from "../../middleware/auth";
import { signupSchema, signinSchema, verifyEmailSchema, resendVerificationSchema, forgotPasswordSchema, resetPasswordSchema, changePasswordSchema } from "./schema";
export const authRoutes = Router();
authRoutes.post("/signup", validateBody(signupSchema), (req, res) => authController.signup(req, res));
authRoutes.post("/signin", validateBody(signinSchema), (req, res) => authController.signin(req, res));
authRoutes.post("/verify-email", validateBody(verifyEmailSchema), (req, res) => authController.verifyEmail(req, res));
authRoutes.post("/resend-verification", validateBody(resendVerificationSchema), (req, res) => authController.resendVerificationEmail(req, res));
authRoutes.post("/forgot-password", validateBody(forgotPasswordSchema), (req, res) => authController.forgotPassword(req, res));
authRoutes.post("/reset-password", validateBody(resetPasswordSchema), (req, res) => authController.resetPassword(req, res));
authRoutes.post("/change-password", requireAuth, validateBody(changePasswordSchema), (req, res) => authController.changePassword(req, res));
authRoutes.post("/refresh", (req, res) => authController.refreshToken(req, res));
authRoutes.post("/logout", (req, res) => authController.logout(req, res));
