import { Router } from "express";
import { notificationsController } from "./controller";
import { requireAuth } from "../../middleware/auth";
import { validateQuery } from "../../middleware/validation";
import { listNotificationsQuerySchema } from "./schema";
export const notificationsRoutes = Router();
notificationsRoutes.use(requireAuth);
notificationsRoutes.get("/", validateQuery(listNotificationsQuerySchema), (req, res) => notificationsController.list(req, res));
notificationsRoutes.get("/:id", (req, res) => notificationsController.getById(req, res));
notificationsRoutes.patch("/:id/read", (req, res) => notificationsController.markAsRead(req, res));
notificationsRoutes.post("/read-all", (req, res) => notificationsController.markAllAsRead(req, res));
